### ISSUE TITLE
Question about others backends

### ISSUE THREAD

**Issue by ricardo-f** [hashicorp/learn-terraform-github-actions#140]
Sorry if my question is explained or resolved in any doc but I'm following this doc:
https://learn.hashicorp.com/tutorials/terraform/github-actions?in=terraform/automation
and I'm curious how the terraform plan section work in a S3 backend for example,
the plan will generate a remote plan at my S3? 
if not, is there any help in how I can "save" the plan from plan step and guarantee the execution of that plan in the apply phase?

**Comment by im2nguyen** [comment]
This issue https://github.com/hashicorp/learn-terraform-github-actions/issues/24 touches adding a manual approval process.

You can also try [Terraform Cloud](https://learn.hashicorp.com/collections/terraform/cloud-get-started). It has a free tier with remote plan/state, GitHub integrations, and more. This [tutorial](https://learn.hashicorp.com/tutorials/terraform/cloud-migrate?in=terraform/state) walks you through migrating your current configuration to Terraform Cloud.

**Comment by ricardo-f** [comment]
Nice, thanks for the tips :)
