### ISSUE TITLE
Fork error given for any issues during the terraform workflow

### ISSUE THREAD

**Issue by nrmzz** [hashicorp/learn-terraform-github-actions#800]
If during the Terraform init, validate, and plan, phases there is an error, the pull request will be closed with the error message related to performing the PR against your personal fork.

For example, if you have a typo in your main.tf, the github action bot will close the pull request stating "Hi! If you are following the Terraform GitHub Actions tutorial, please open the PR against [your personal fork] of this repository. We will automatically close this PR, but if you intended to edit the example itself please feel free to re-open it"

It will not be immediately apparent to new users that the issue is actually related to the terraform init or terraform plan stages and could cause some confusion (at least it did for me). 

For example:  https://github.com/nrmzz/NRMZ-learn-terraform-github-actions/pull/2

**Comment by judithpatudith** [comment]
Oh interesting!! Thank you for this report! Just to confirm, the issue is that when you forked the repo the github action came along with it, and now you can't open PRs to your fork without getting rid of the action first? Thanks for the report!

**Comment by ritsok** [comment]
Thanks for reporting this! We've resolved the issue.
