### ISSUE TITLE
Terraform syntax highlighting

### ISSUE THREAD

**Issue by WDaan** [hashicorp/learn-terraform-github-actions#905]
### Description
The current syntax highlighting in the markdown is broken. See https://github.com/hashicorp/learn-terraform-github-actions/pull/906 for a possible fix.

Another option is to render the plan output using `diff` so the changes will show up as colorised colorised blocks. It provides a better overview of what happened, but unfortunately loses the terraform syntax highlighting. 
See https://github.com/hashicorp/learn-terraform-github-actions/pull/904

The best option would be of course both, get colorised blocks but also keep the syntax highlighting. Unfortunately haven't found a way to do that yet.

Let me know what you think.

**Comment by F21** [comment]
If you're still looking for a way to do syntax highlighting on PR comments, you can try this action: https://github.com/robburger/terraform-pr-commenter

The downside is that you'd need to bring in another action, but the syntax highlighting on plans makes them much more usable.

**Comment by WDaan** [comment]
Thanks, seems like that action is using my first solution using diff.

**Comment by alanszlosek** [comment]
@WDaan Thanks for reporting this. We recently fixed this with [295ad79b72f6c9dbf565b1a7e76fa53a4c671ba8. ](https://github.com/hashicorp/learn-terraform-github-actions/commit/295ad79b72f6c9dbf565b1a7e76fa53a4c671ba8) as you suggested in #906.
